BLOCK: neural_eq_top_final
NDM_DATABASE: ../../../pnr/2_design_library/output/neural_eq_top.dlib
NETLIST_FILE: neural_eq_top_cmax_tm40.spef
MAPPING_FILE: /home/standard_cell_libraries/NangateOpenCellLibrary_PDKv1_3_v2010_12/tech/rcxt/FreePDK45_10m.map
TCAD_GRD_FILE:  /home/standard_cell_libraries/NangateOpenCellLibrary_PDKv1_3_v2010_12/tech/rcxt/FreePDK45_10m_Cmax.nxtgrd
OPERATING_TEMPERATURE: -40
STAR_DIRECTORY: star
SUMMARY_FILE: ./rcxt.log
BUS_BIT: []
COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
EXTRACTION: RC
HIERARCHICAL_SEPARATOR: /
METAL_FILL_POLYGON_HANDLING: FLOATING
NETLIST_FORMAT: SPEF
NETS: *
MODE: 400
REDUCTION: YES
MILKYWAY_EXPAND_HIERARCHICAL_CELLS: YES
