########################################################################
# ECO Stage - ICC2
########################################################################
set design neural_eq_top

# 1. Open the existing design library and the final routed block
open_lib ../2_design_library/output/${design}.dlib
open_block ${design}_final

# 2. Source the ECO changes generated by PrimeTime
# We source both setup and hold fixes if they exist
puts "INFO: Checking for PrimeTime ECO scripts..."
if {[file exists ../../qor/sta/max/hazem_fix_setup.tcl]} {
    puts "INFO: Sourcing Setup ECO changes from PT..."
    source ../../qor/sta/max/hazem_fix_setup.tcl
}

if {[file exists ../../qor/sta/min/hazem_fix_hold.tcl]} {
    puts "INFO: Sourcing Hold ECO changes from PT..."
    source ../../qor/sta/min/hazem_fix_hold.tcl
}

# 3. Connect PG for newly inserted cells
connect_pg_net -automatic

# 4. Place and Route ECO changes
puts "INFO: Placing ECO cells..."
place_eco_cells -legalize_only

puts "INFO: Routing ECO nets..."
route_eco -utilize_dangling_wires true

# 5. Route Optimization / DRC fixing if needed
route_detail -incremental true

# 6. Re-insert Fillers
puts "INFO: Removing old fillers and re-inserting..."
# Using quiet mode in case no fillers are found
remove_cells -quiet [get_cells -hierarchical -filter "ref_name =~ FILLCELL*"]

create_stdcell_fillers -lib_cells {NangateOpenCellLibrary_physical_only/FILLCELL_X32 NangateOpenCellLibrary_physical_only/FILLCELL_X16 NangateOpenCellLibrary_physical_only/FILLCELL_X8 NangateOpenCellLibrary_physical_only/FILLCELL_X4 NangateOpenCellLibrary_physical_only/FILLCELL_X2 NangateOpenCellLibrary_physical_only/FILLCELL_X1}
connect_pg_net -automatic

# 7. Verification
check_routes
check_pg_drc

# 8. Output generation
file mkdir output
set PDK_ROOT "/home/standard_cell_libraries/NangateOpenCellLibrary_PDKv1_3_v2010_12"

puts "INFO: Writing GDS and Verilog for ECO iteration..."
write_gds -layer_map "$PDK_ROOT/tech/strmout/FreePDK45_10m_gdsout.map" \
          -fill include \
          -output_pin all \
          ./output/${design}_eco.gds

write_verilog -include {pg_netlist} ./output/${design}_eco_pg.v
write_verilog ./output/${design}_eco_nopg.v

# Write parasitic SPEF for the next ECO loop iteration (if needed)
write_parasitics -format SPEF -output ./output/${design}_eco.spef

save_block -as ${design}_eco
close_lib

puts "INFO: ECO implementation complete."
exit
